### ISSUE TITLE
Shipment Request Error

### ISSUE THREAD

**Issue by palak07** [chirag7jain/bluedart#1]
@chirag7jain  look into this ! 

{:error=>true, :error_text=>{:code=>{:value=>"s:Sender", :subcode=>{:value=>"a:DeserializationFailed"}}, :reason=>{:text=>"The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://tempuri.org/:Request. The InnerException message was 'There was an error deserializing the object of type SAPI.Entities.WayBillGeneration.WayBillGenerationRequest. The value '' cannot be parsed as the type 'double'.'.  Please see InnerException for more details."}}}

my code is here : 
shipment_details = {mode: "development"}

shipment_details[:creds] = {license_key: "xyz", login_id: "xyz"}

shipment_details[:shipper_details] = {customer_code:111, customer_name: "J Bieber", address: "ABC ABC", customer_pincode:"400086",customer_telephone: 123123, customer_mobile:9594964558,  customer_email_id:"someone@me.com", sender:"bla bla", vendor_code:2323, isToPayCustomer:false, origin_area:"AAA"}

shipment_details[:consignee_details] = {consignee_name:"Ninja", address:"hogsmeade station", consignee_pincode:"400067", consignee_telephone:"02228551577", consignee_mobile: "9594964000", consignee_attention:"none"}

shipment_details[:services] = {piece_count:1, actual_weight:1, pack_type:"box", invoice_no:"2121", special_instruction:"none", declared_value:9999, credit_reference_no:9999, dimensions:[{:breadth=>1,:height=>2,:length=>1,:count=>1}], pickup_date:"2016-4-30", pickup_time: Time.now + 1.days, commodities:["Crack"], product_type:"Dutiables", collectable_amount:5050, product_code:"A", sub_product_code:"C", p_d_f_output_not_required:false}

b = Bluedart::Shipment.new(shipment_details)

b.response

**Comment by chirag7jain** [comment]
There probably has been a change in their API and they have not ensured backwards compatibility. 

I am currently not maintaining this gem but I can help you resolve this issue and you can submit a pull request for the changes.

if your interested what you can do is

Add byebug in base.rb (within bluedart gem file) - make_request function around line 183. Get the xml body of the request and send it to bluedart for inspection for errors and then make the changes as requested

**Comment by palak07** [comment]
also .. 
checkout like number 69 in shipment.rb
should it be 
params['Dimensions'] = dimensions_hash(details[:diemensions])

**Comment by chirag7jain** [comment]
I know about the typo

that was how it was mentioned in their documentation and at the time when i wrote the gem it was working.

**Comment by chirag7jain** [comment]
if you read the error carefully it says that there a value / values that needs to be "double" - datatype

'There was an error deserializing the object of type SAPI.Entities.WayBillGeneration.WayBillGenerationRequest. The value '' cannot be parsed as the type 'double'.'. Please see InnerException for more details."}}}

i think its the actual weight attribute

**Comment by chirag7jain** [comment]
@palak07 I will close it unless you have any thing further to add

**Comment by chirag7jain** [comment]
@palak07 was ur issue resolved.
